#!/bin/bash -e
if [ "$1" = 'remove' ] || [ "$1" = 'purge' ] || [ "$1" = 'disappear' ]; then
  rm -rf /opt/opentelemetry_shell
elif [ "$1" = 'upgrade' ]; then
  # nothing to do
elif [ "$1" = 'failed-upgrade' ] || [ "$1" = 'abort-install' ] || [ "$1" = 'abort-upgrade' ]; then
  # nothing to do
else
  exit 1
fi
