#!/bin/bash -e
if [ "$1" = 'remove' ] || [ "$1" = 'deconfigure' ] || [ "$1" = 'upgrade' ]; then
  ls /opt/opentelemetry_shell/
  rm -rf /opt/opentelemetry_shell/venv_sdk /opt/opentelemetry_shell/*.so /opt/opentelemetry_shell/venv /usr/share/opentelemetry_shell/node_modules
elif [ "$1" = 'failed-upgrade' ]; then
  true
else
  exit 1
fi
