#!/bin/sh -e
if [ "$1" = 0 ]; then set -- remove; fi
if [ "$1" = 1 ]; then set -- upgrade; fi
if [ "$1" = 'remove' ] || [ "$1" = 'deconfigure' ] || [ "$1" = 'upgrade' ]; then
  rm -rf /opt/opentelemetry_shell/sdk/venv /opt/opentelemetry_shell/*.so /opt/opentelemetry_shell/venv /opt/opentelemetry_shell/node_modules /usr/share/opentelemetry_shell/node_modules
elif [ "$1" = 'failed-upgrade' ]; then
  true
else
  exit 1
fi
