name: 'OpenTelemetry Jobs'
description: 'Observe Github Jobs with OpenTelemetry'
branding:
  icon: 'activity'
  color: 'blue'
runs:
  using: 'node20'
  pre: 'inject_and_init.js'
  main: 'nop.js'
  post: 'shutdown.js'
inputs:
  github_token:
    description: 'A GitHub token for API access (read-only)'
    default: '${{ github.token }}'
  cache:
    description: 'Whether to use GitHub Actions Cache to cache dependencies'
    default: true
  collector:
    description: 'Whether to use a collector hide potentially sensitive secrets from other actions'
    default: auto
  debug:
    description: 'Enable debug logging'
    default: ${{ runner.debug }}
  __job_status:
    description: 'INTERNAL ONLY - DO NOT SET MANUALLY'
    default: '${{ job.status }}'
  __job_matrix:
    description: 'INTERNAL ONLY - DO NOT SET MANUALLY'
    default: '${{ toJSON(matrix) }}'
